name: GJTestPage
favicon: null
layout_spectrum: 0.24976
typography_spectrum: 0.74233
title: Practice page for DIGESTED
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c1560'
    - '#5e7698'
    - '#7aa9c5'
    - '#ecac7c'
  brandStrength: 0.5
  lightness: 0.7896029590629041
  saturation: 0.42342484137043357
  rhythmicContrast: 0.3032456065993756
purpose: []
